Added How to setup stage-file-proxy
druidfi/guidelines pull request #8
Opened 2022-09-29 09:48 UTC by laurielim

In this PR:
- added new guideline in /docs
- updated readme

2022-09-29 09:57 UTC, back-2-95 commented on docs/drupal_stage_file_proxy.md
> +4.  Create project specific make file in `tools/make/project`, for example `stage-file-proxy.mk`
Whole 4. can be replace with

Add these lines to .env file:

```
# Enable these modules on local
DRUPAL_ENABLE_MODULES="stage_file_proxy"
```

2022-09-29 14:54 UTC, laurielim commented on docs/drupal_stage_file_proxy.md
> +4.  Create project specific make file in `tools/make/project`, for example `stage-file-proxy.mk`
Did the change

2022-10-11 04:13 UTC, back-2-95 commented on docs/drupal_stage_file_proxy.md
> +3.  Exclude module configurations. Modify `public/sites/default/settings.php` and add
"Or if Omen is used, it does this for you"

2022-10-11 04:15 UTC, back-2-95 commented on docs/drupal_stage_file_proxy.md
> +Stage File Proxy lets you update the database of your local development instance without having to update your files directory. Stage File Proxy transfers each requested file just in time when it is
"update the database" is not correct. This module basically converts urls on files when links are rendered. Thus it does not work anything which might be added to e.g. templates without using proper Drupal url generation functions.

2022-10-11 04:15 UTC, back-2-95 requested changes
See the comments

2022-11-22 13:09 UTC, laurielim commented on docs/drupal_stage_file_proxy.md
> +3.  Exclude module configurations. Modify `public/sites/default/settings.php` and add
Not sure which part Omen does; #3?

2022-11-22 13:12 UTC, back-2-95 commented on docs/drupal_stage_file_proxy.md
> +3.  Exclude module configurations. Modify `public/sites/default/settings.php` and add
Omen excludes stage_file_proxy settings from configuration export.

2022-11-22 13:12 UTC, laurielim commented on docs/drupal_stage_file_proxy.md
> +Stage File Proxy lets you update the database of your local development instance without having to update your files directory. Stage File Proxy transfers each requested file just in time when it is
I just copied the module description from https://www.drupal.org/project/stage_file_proxy. i could remove that first line if it is problematic.

2022-11-22 13:14 UTC, back-2-95 commented on docs/drupal_stage_file_proxy.md
> +Stage File Proxy lets you update the database of your local development instance without having to update your files directory. Stage File Proxy transfers each requested file just in time when it is
Yeah, that 1st line is misleading.

2022-12-16 09:15 UTC, laurielim commented on docs/drupal_stage_file_proxy.md
> +3.  Exclude module configurations. Modify `public/sites/default/settings.php` and add
Removed step 3

2022-12-16 09:19 UTC, merged